version: "3.9"

services:
  app:
    container_name: drone-fleet
    image: dpimkin/drone-fleet:1.0.0
    links:
      - psql_db:app_db
    ports:
      - '8088:8088'
    restart: always
    depends_on:
      - psql_db

  psql_db:
    container_name: drone-fleet-db
    image: postgres:13.7-alpine
    environment:
      POSTGRES_DB: fleet_db
      POSTGRES_USER: alt_cunningham
      POSTGRES_PASSWORD: s0ulki113r
    ports:
     - '5432:5432'
    restart: always

