spring:
  application:
    name: drone-fleet
  r2dbc:
    url: r2dbc:pool:postgresql://${DB_HOST}:5432/fleet_db?loggerLevel=OFF
    username: alt_cunningham
    password: s0ulki113r
  flyway:
    url: jdbc:postgresql://${DB_HOST}:5432/fleet_db?loggerLevel=OFF
    user: alt_cunningham
    password: s0ulki113r
    driver-class-name: org.postgresql.Driver
  cache:
    cache-names: drone-cache
    caffeine.spec: maximumSize=500,expireAfterAccess=60s

management:
  endpoint.health.show-details: always
  endpoints:
    enabled-by-default: true
    web.exposure.include: "health,metrics"
    jmx.exposure.exclude: "*"

drone-fleet:
  audit.rateMs: 120000
  low-battery-threshold: 25

springdoc:
  enable-hateoas: false
  cache.disabled: true
  show-actuator: true

server:
  port: 8088

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    com.musalasoft.dronefleet: DEBUG

