spring:
  application:
    name: drone-fleet
  r2dbc:
    url: r2dbc:pool:postgresql://app_db:5432/fleet_db?loggerLevel=OFF
    username: alt_cunningham
    password: s0ulki113r
  flyway:
    url: jdbc:postgresql://app_db:5432/fleet_db?loggerLevel=OFF
    user: alt_cunningham
    password: s0ulki113r
    driver-class-name: org.postgresql.Driver

springdoc:
  enable-hateoas: false
  cache.disabled: true
  show-actuator: true

server:
  port: 8088

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    com.musalasoft.dronefleet: DEBUG

