spring:
  application:
    name: drone-fleet
springdoc:
  use-management:
    port: true
server:
  port: 8088

drone-fleet:
  low-battery-threshold: 25

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
